[package]
name = "protos"
version = "0.1.0"
edition = "2021"

#[features]
#default = ["proto_full"]

[dependencies]
bytes = "1.5.0"
pbjson = "0.6.0"
pbjson-types = "0.6.0"
prost = "0.12.3"
serde = "1.0.197"
tonic = { version = "0.11.0", features = ["gzip"] }
